app:
  eureka-server: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # discovery-service routeing
        - id: discovery-service
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-service-static
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**
        # user-service routing
        - id: users-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AddResponseHeader=X-Powered-By, StudentSpace Gateway Service
        # administration-service routing
        - id: administration-service
          uri: lb://administration-service
          predicates:
            - Path=/api/v1/administration/**
          filters:
            - AddResponseHeader=X-Powered-By, StudentSpace Gateway Service
        # scene-service routing
        - id: scene-service
          uri: lb://scene-service
          predicates:
            - Path=/api/v1/scenes/**
          filters:
            - AddResponseHeader=X-Powered-By, StudentSpace Gateway Service
        # forum-service routing
        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/api/v1/forum/**
          filters:
            - AddResponseHeader=X-Powered-By, StudentSpace Gateway Service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/StudentSpace
  application:
    name: api-gateway

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: API Gateway Service
        url: /v3/api-docs
      - name: User Service API
        url: /api/user/v3/api-docs
      - name: Administration Service API
        url: /api/administration/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka
