app:
  eureka-server: localhost
  keycloak-url: ${KEYCLOAK_URL}

server:
  port: 0

spring:
  application:
    name: scene-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak-url}/realms/StudentSpace
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cloud:
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=100,maximumSize=500,expireAfterAccess=600s
      health-check:
        path:
          default: /


logging:
  level:
    root: info
    sql: info
    web: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: info
      hibernate: info
      com:
        example:
          administration: info
  file:
    name: ./logs/scene-service.log
    path: ./logs/

management:
  health:
    circuitbreakers:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://${app.keycloak-url}:8761/eureka

#Resilinece4j Properties for Admin Service
resilience4j:
  circuitbreaker:
    instances:
      services:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.HttpClientErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.lang.Exception
          - java.lang.RuntimeException
          - java.lang.Throwable
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - java.lang.IllegalStateException
          - java.lang.RuntimeException
          - java.lang.Throwable