app:
  eureka-server: localhost
  keycloak-url: http://138.3.248.186:8888


server:
  port: 0

spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak-url}/realms/StudentSpace
