app:
  keycloak-url: ${KEYCLOAK_URL}
  keycloak-client-id: ${KEYCLOAK_CLIENT_ID}
  keycloak-client-secret: ${KEYCLOAK_CLIENT_SECRET}
  keycloak-realm: ${KEYCLOAK_REALM}
  eureka-server: localhost

spring:
  application:
    name: administration-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/StudentSpace
server:
  port: 0

springdoc:
  api-docs:
    path: /api/v1/administration/v3/api-docs
  swagger-ui:
    path: /api/v1/administration/swagger-ui.html

logging:
  level:
    root: info
    sql: info
    web: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: info
      hibernate: info
      com:
        example:
          administration: info
  file:
    name: ./logs/administration-service.log
    path: ./logs/

management:
  health:
    circuitbreakers:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka
